[[https://www.notion.so/Rulebook-fd1063d6d8164439a72d34fc8221b514][Rules Doc in Octoraffe Notion]]

* Nouns
- action
- action group
- autograph tag
- bagged pile (player’s comics)
- bargain bin deck
- bargain bin discard
- comic
- comic company
- comic supply
- comic supply discard
- game-end token
- general supply
- grading token
- hero track
- hero value
- loose pile (player’s comics)
- player board
- smudge token
- superpower card
- time cost
- time cube
- travel section (board location)
- turn order token
- turn order track
- unique hero token
- used row (place)
* Verbs
- claim an action
- boost an action
- draft
- discard
- draw
- buy
- claim [an action]
- assign [time cubes]
* Actions
** Store
*** Reserve Loose
Pay half of the current market value of the `comic and place it in your loose pile.

*** Sell
Each `action row` in this `action group` has a number next to it. This represents the number of comics you may sell.

Select any of your `comics`, up to the maximum allowed. Collect <<coins>> equal to their `hero value` adjusting for the following:

 - `Loose Comics` sell for half (1/2) their `hero value'
 - `Bagged Comics` sell for  `hero value`
 - `Displayed Comics` sell for `hero value`
 - `Autographed comics` sell for double `hero value` or $0.30, whichever is higher.

After you you have collected all of the <<coins>> owed to you, place the sold `comics` into the reserve row, starting with the right most empty space. If you would need to place a comic and the reserve row is full, move the right most comic into the `bargain bin discard`.

Continue this process, in the order of your choosing, until all `comics` have been placed in the reserve row. 

(h4.) Sell Boost
You may boost the Sell action to increase the maximum number of comics may sell when resolving it. Each cube increases the maximum by 2.



*** Reserve New
Pay the full `hero value` of the `comic` and place it in your `bagged pile`




Until the game end is triggered, each time a new hero is displayed, the player who displayed that hero gains a superpower. Note that the game-end token is on the  game begins with a number of superpower cards equal to the number of unique heroes that triggers the end of the game.

Until the game end is triggered, each time a new hero is displayed, the player who displayed that hero gains a superpower. Note that there are a number of superpower cards added to the starting pool


